modLoader="javafml" #mandatory

loaderVersion="[47,)" #mandatory

license="MIT"

[[mods]] #mandatory

modId="nohung" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Retro Hunger Mod" #mandatory

logoFile="examplemod.png" #optional

authors="Nero" #optional

description='''
long Description
'''

[[dependencies.nohung]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[47.3.0,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.nohung]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
